### ISSUE TITLE
요청:Member Repository 오타

### ISSUE THREAD

**Issue by choideakook** [choideakook/BaekJoon_Supporter#34]
### Issue: 📌 request  
요청 기능 요약을 입력해 주세요.
<br>
- 오타 수정 부탁드립니다!
 

  
  
### 📌 Todo
요구사항을 작성해 주세요.
 
- member repository 메서드
findByMemberName 에서 findByName 으로 수정 부탁드립니다!
  
  
### 📌 ETC
기타 사항을 입력해 주세요
<br>
<img width="766" alt="스크린샷 2023-03-31 오후 7 43 35" src="https://user-images.githubusercontent.com/115536240/229099562-4802e1b2-e46e-40a4-a8b2-70e846a79d52.png">
<img width="234" alt="스크린샷 2023-03-31 오후 7 42 16" src="https://user-images.githubusercontent.com/115536240/229099566-587faf49-3615-4a2e-9393-4fd60f8ffc4a.png">
<img width="615" alt="스크린샷 2023-03-31 오후 7 42 07" src="https://user-images.githubusercontent.com/115536240/229099571-e2e4c0c6-cb97-42a3-87a1-cf4075897dc0.png">

**Comment by yurrrrri** [comment]
수정하고 PR 올렸습니다!
