### ISSUE TITLE
필드값 수정 요청

### ISSUE THREAD

**Issue by choideakook** [choideakook/BaekJoon_Supporter#9]
잘 작동되는지 확인해보려고 app 을 실행시켜 봤는데 예외가 발생해서 확인해보니
<br>
`Comment` 엔티티의 필드중 `desc` 는 사용할 수 없는 이름이라고 합니다 ㅜㅜ
<br>
`desc` 대신 다른 이름으로 교체 부탁드리겠습니다 ㅜㅜ

**Comment by PARKPARKWOO** [comment]
네 ㅎㅎ 수정 해서 올리겠습니다
